blueprint:
  name: Kaffeemaschine – Erinnerung nach Laufzeit (iOS interaktiv)
  description: >
    Überwacht einen Schalter (z. B. Kaffeemaschine). 
    Wenn er länger als die eingestellte Zeit eingeschaltet bleibt 
    (Standard: 40 Minuten), werden interaktive iOS-Benachrichtigungen verschickt.  
    Du kannst dann auswählen: **An lassen** oder **Ausschalten**.  
    Reagierst du nicht, wird nach Ablauf der Antwortzeit (Standard: 5 Minuten) 
    automatisch ausgeschaltet.  
    In allen Fällen wird die Benachrichtigung anschließend aufgeräumt.
  domain: automation
  source_url: https://github.com/Maneridiet/home-assistant-blueprints#coffee-prompt

input:
  coffee_switch:
    name: Kaffeemaschinen-Schalter
    description: Wähle den Schalter aus, der überwacht und ggf. automatisch ausgeschaltet werden soll.
    selector:
      entity:
        domain: switch

  run_time:
    name: Laufzeit bis zur Erinnerung
    description: Dauer, die der Schalter eingeschaltet sein muss, bevor die Benachrichtigung gesendet wird.
    default: "00:40:00"
    selector:
      duration: {}

  response_timeout:
    name: Antwort-Zeitfenster
    description: Wie lange nach der Benachrichtigung auf eine Antwort gewartet werden soll, bevor automatisch ausgeschaltet wird.
    default: "00:05:00"
    selector:
      duration: {}

  notify_devices:
    name: Zielgeräte (iOS)
    description: Wähle ein oder mehrere iPhones/iPads (Home Assistant Companion App), an die die Push-Benachrichtigung gesendet wird.
    selector:
      device:
        multiple: true
        filter:
          integration: mobile_app

  notification_tag:
    name: Benachrichtigungs-Tag
    description: Kennung, mit der die Benachrichtigung später wieder geschlossen werden kann. Standard: `coffee_prompt`.
    default: coffee_prompt
    selector:
      text: {}

  title_running:
    name: Titel – Erinnerung
    description: Überschrift der Benachrichtigung, wenn die Kaffeemaschine lange läuft.
    default: Kaffeemaschine läuft seit 40 Minuten
    selector:
      text: {}

  message_running:
    name: Text – Erinnerung
    description: Nachrichtentext der Benachrichtigung.  
    Tipp: Erkläre, wie man die Aktion auswählt (z. B. „Zum Auswählen lange drücken“).
    default: "Zum Auswählen lange drücken: An lassen oder Ausschalten"
    selector:
      text: {}

  title_auto_off:
    name: Titel – automatisch ausgeschaltet
    description: Überschrift der Benachrichtigung, wenn automatisch ausgeschaltet wurde.
    default: Kaffeemaschine ausgeschaltet
    selector:
      text: {}

  message_auto_off:
    name: Text – automatisch ausgeschaltet
    description: Nachrichtentext, wenn automatisch ausgeschaltet wurde (z. B. nach Timeout).
    default: Keine Antwort nach 5 Minuten – wurde automatisch ausgeschaltet.
    selector:
      text: {}

  keep_title:
    name: Aktionstext – An lassen
    description: Text für die Schaltfläche, um die Kaffeemaschine eingeschaltet zu lassen.
    default: An lassen
    selector:
      text: {}

  off_title:
    name: Aktionstext – Ausschalten
    description: Text für die Schaltfläche, um die Kaffeemaschine auszuschalten.
    default: Ausschalten
    selector:
      text: {}
